# Generated by Django 3.1.5 on 2021-01-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('score_id', models.AutoField(primary_key=True, serialize=False, verbose_name='成绩id')),
                ('zkzh', models.CharField(max_length=12, verbose_name='课程代号')),
                ('kcmc', models.CharField(max_length=20, verbose_name='课程名称')),
                ('cj', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='成绩')),
                ('ksrq', models.CharField(max_length=12, verbose_name='考试日期')),
                ('bz', models.CharField(max_length=12, verbose_name='备注')),
                ('is_subscribed', models.BooleanField(default=False, verbose_name='是否已发送')),
            ],
            options={
                'verbose_name': '成绩表',
                'verbose_name_plural': '成绩表',
                'db_table': 'tb_scores',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False, verbose_name='学生id')),
                ('zkzh', models.CharField(max_length=12, verbose_name='准考证号')),
                ('student_name', models.CharField(max_length=8, verbose_name='姓名')),
                ('student_email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('is_exist', models.BooleanField(default=True, verbose_name='是否存在')),
                ('is_subscribe', models.BooleanField(default=False, verbose_name='是否订阅新成绩')),
                ('is_remind_details', models.BooleanField(default=False, verbose_name='是否实时检查新成绩')),
                ('signup_date', models.DateTimeField(null=True, verbose_name='注册日期')),
                ('last_signin_date', models.DateTimeField(null=True, verbose_name='上一次登陆时间')),
                ('signup_ip', models.CharField(blank=True, max_length=36, null=True, verbose_name='注册IP')),
                ('last_signin_ip', models.CharField(blank=True, max_length=36, null=True, verbose_name='上一次登陆IP')),
                ('priority', models.IntegerField(default=100000, verbose_name='通知优先级')),
            ],
            options={
                'verbose_name': '学生表',
                'verbose_name_plural': '学生表',
                'db_table': 'tb_students',
            },
        ),
    ]
