# Generated by Django 3.1.5 on 2021-01-25 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInterface', '0002_auto_20210122_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCheckCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('checkcode', models.CharField(max_length=18)),
                ('statu', models.PositiveSmallIntegerField(default=0, verbose_name='验证码状态')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('guoqi_data', models.DateTimeField(verbose_name='过期日期')),
            ],
            options={
                'verbose_name': '邮箱验证码',
                'verbose_name_plural': '邮箱验证码',
                'ordering': ['-add_date'],
            },
        ),
        migrations.AddField(
            model_name='students',
            name='cookies',
            field=models.CharField(max_length=256, null=True, verbose_name='Cookie'),
        ),
        migrations.AddField(
            model_name='students',
            name='cookies_timeout',
            field=models.DateTimeField(null=True, verbose_name='Cookie过期时间'),
        ),
        migrations.AlterUniqueTogether(
            name='students',
            unique_together={('student_id', 'zkzh')},
        ),
    ]
