# Generated by Django 3.1.5 on 2021-01-25 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInterface', '0003_auto_20210125_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='student_name',
            field=models.CharField(max_length=16, verbose_name='姓名'),
        ),
    ]
