# Generated by Django 3.1.5 on 2021-01-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInterface', '0004_auto_20210125_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='signup_location',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='注册位置'),
        ),
        migrations.AddField(
            model_name='students',
            name='student_img',
            field=models.CharField(default=1234567890123456, max_length=16, verbose_name='学生头像'),
            preserve_default=False,
        ),
    ]
